## This script cannot download image from docker image registry because
## the digest is not complete.
## Please do use the digest generated by Docker rather than cut it into short.

IMG_NAME=docker.tutorials:docker-image-version-short
export DOCKER_BUILDKIT=1

echo "Start to build docker image from: " && pwd

VERSION=sha256:b9f3323
SOURCE=ghcr.io/ottohung/docker.tutorials:git-https@${VERSION}

# Tilde(~) doesn't work for `buildx`, please use `$HOME` instead.
# The name of build context must be lowercase.
docker buildx build \
   --build-context image=docker-image://${SOURCE} \
   --no-cache \
   -t ${IMG_NAME} \
   -f ./dockerfiles/build-contexts/docker-image/Dockerfile .
